eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
        
spring:        
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/mybillbook?allowPublicKeyRetrieval=TRUE
    username: root
